### ISSUE TITLE
BoatApp

### ISSUE THREAD

**Issue by Pantyhose-X** [ShirosakiMio/MioProFile#1]
1、澪-b4.8.apk 你可以上传到 GitHub releases " releases上传文件大小限制2GB"

2、你可以弄个地图转换工具吗? 我的世界 转换成 https://www.minetest.net
参考
https://forum.minetest.net/viewtopic.php?f=12&t=13709&sid=64ab4a65e2791ce2b615a536130c7014

https://forum.minetest.net/viewtopic.php?f=14&t=14271&sid=3cd2c3fc6dedd9d79bdc4bf396b1b7d9

**Comment by ShirosakiMio** [comment]
懒得在github更新，不挂梯子国内不好下

**Comment by Pantyhose-X** [comment]
> 懒得在github更新，不挂梯子国内不好下

我要IDM  ADM  多线程下载很快啊

**Comment by xiaohan316** [comment]
确实不挂梯子要下好长时间还会失败
